### ISSUE TITLE
wrappr.wrap does not work

### ISSUE THREAD

**Issue by zangguojun** [sffc/word-wrappr#10]
Please run the demo below.
```js
const WordWrappr = require("word-wrappr")

// CONST
const fontSize = 42
const width = 720

// init
const wrappr = new WordWrappr()
wrappr.loadSync()

const lines = wrappr.wrap(
  "aaaaaaaaaaaaaddsadfeefhdshfsdfisdhfisdhifsdifhdsisdi",
  fontSize,
  width
)
console.log(lines)
const computeWidth = wrappr.computeWidth(
  "aaaaaaaaaaaaaddsadfeefhdshfsdfisdhfisdhifsdifhdsisdi",
  fontSize
)
console.log(computeWidth)
```

output
```
>> [ 'aaaaaaaaaaaaaddsadfeefhdshfsdfisdhfisdhifsdifhdsisdi' ]
>> 1160.2705078125
```
Result : the width(=720) < the computeWidth result(1160.2705078125)
But the function(wrappr.wrap) does not work, and return an array with only one item.

**Comment by zangguojun** [comment]
Another Question:
I ran the following command you wrote in your README.
```
npm install -g word-wrappr
wrappr --help
```
However, an error is reported here, as shown below
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/49148972/171606537-04d8c83c-dbdd-453d-bc95-66ce6043980d.png">

**Comment by zangguojun** [comment]
> Please run the demo below.
> 
> ```js
> const WordWrappr = require("word-wrappr")
> 
> // CONST
> const fontSize = 42
> const width = 720
> 
> // init
> const wrappr = new WordWrappr()
> wrappr.loadSync()
> 
> const lines = wrappr.wrap(
>   "aaaaaaaaaaaaaddsadfeefhdshfsdfisdhfisdhifsdifhdsisdi",
>   fontSize,
>   width
> )
> console.log(lines)
> const computeWidth = wrappr.computeWidth(
>   "aaaaaaaaaaaaaddsadfeefhdshfsdfisdhfisdhifsdifhdsisdi",
>   fontSize
> )
> console.log(computeWidth)
> ```
> 
> output
> 
> ```
> >> [ 'aaaaaaaaaaaaaddsadfeefhdshfsdfisdhfisdhifsdifhdsisdi' ]
> >> 1160.2705078125
> ```
> 
> Result : the width(=720) < the computeWidth result(1160.2705078125) But the function(wrappr.wrap) does not work, and return an array with only one item.

I know , A word cannot be divided!

**Comment by zangguojun** [comment]
Then this will not apply to other languages that do not often use spaces, like chinese.such as “就比如这句话，没有任何空格”
So, can you provide a configuration to specify word segmentation rules? 

For chinese:
1, Replace “ ”(spaces) with "，。！；"(Punctuation in Chinese)
OR
2, Use a to preprocess text

**Comment by sffc** [comment]
You are right. There are two bugs you found:

1.`wrappr` only wraps at word boundaries, not inside words. Bug: https://github.com/sffc/word-wrappr/issues/4
2. `wrappr` uses spaces to find word boundaries, but it should use UTR 14 and ICU instead. Bug: https://github.com/sffc/word-wrappr/issues/12

I will close this issue and track the feature requests in #4 and #12.
